### ISSUE TITLE
Migrate GitLab CI to GitHub Actions

### ISSUE THREAD

**Issue by pnadolny13** [meltano/squared#250]
Test: On PRs, merges and main
- Airflow
- SqlFluff
- EL Sync
- DBT deps/seed/run/test
- Reverse EL Sync

Docker: On merges to main, depends on tests
- Build docker images
- Push to ECR

Terraform: On merge to main, depends on Docker
- validate
- plan
- deploy

dbt Deploy: On merge to main, depends on Terraform
- seed
- docs deploy

Snowflake CI Cleanup: scheduled
- delete stale CI Snowflake schemas

**Comment by pnadolny13** [comment]
It seems like the structure of your CI project is pretty flexible so I wanted to see if anyone had thoughts/recommendations before I make any changes.

I was planning to split each one of the headers above into its own workflow yaml. For the `Test` workflow EL/dbt/Reverse EL all need to run in order so I was planning to have them as dependent tasks in the same workflow. The Airflow and SqlFluff jobs are dependencies for the EL test to start but can run in parallel because neither rely on each other. Do you think its better to have those 2 jobs be independent workflows to run in parallel? It seems like a workflow uses the same runner so it would increase setup time because we now have 3 workflow environments to start up (i.e. Airflow/SqlFluff/Others) vs just one if theyre all bundled on one runner.

Is there anything im not considering? Is there a better way to set these up in terms of jobs vs workflows?

**Comment by pnadolny13** [comment]
Another thing I want to consider is how we can make this generic enough to share out to the community for re-use. That makes me want to split each test job out into its own workflow so users could optionally remove pieces they dont need. Or we could just give instructions to delete steps that arent being used "if you dont use sqlfluff, delete the sqlfluff job".

**Comment by aaronsteers** [comment]
@pnadolny13 - I think you may want to break this into a few different issues. 

I would do at least one for "CI tests" which by their nature would target ephemeral+disposable environments, and another for prod deployment.

The prod deployment part won't be very reusable per se, but the CI tests should be very reusable.

**Comment by aaronsteers** [comment]
- https://github.com/meltano/meltano-run-action/issues/1
