### ISSUE TITLE
Fix Unique Pipelines Metric

### ISSUE THREAD

**Issue by pnadolny13** [meltano/squared#269]
The unique pipelines metric is broken following the switch to unstructured events. I incorporated the struct + unstruct events into many of the other dashboards/metrics but this one was relying on the old struct command to determine uniqueness, and we dont get that anymore.

I'm considering moving to using a list of plugins + environment hash + project_id as defining a unique pipeline because that was the inferred pieces of the original value. From a quick query the numbers drop following this switch so I'm not sure whats making them look the same using the name formula vs different with the old command. We should look into it and get the metric updated.

**Comment by DouweM** [comment]
Discussion: https://github.com/meltano/internal-data/discussions/2

**Comment by pnadolny13** [comment]
The outcome of https://github.com/meltano/internal-data/discussions/2 which was primarily around handling invoke properly as it relates to counting pipelines.

The outcome is to exclude invoke from the definition of a pipeline. The trade off is that many users execute dbt directly using invoke but were fine with only tracking pipelines as elt/run because thats what schedules use.

- implement plugins x project ID x environment as unique pipeline
- only include elt and run commands
- document the decision to exclude invoke in the handbook metrics page
