### ISSUE TITLE
Ingest Hub Plugin Definitions

### ISSUE THREAD

**Issue by pnadolny13** [meltano/squared#275]
Potentially use a variation of https://github.com/AutoIDM/tap-meltanohub to pull from the new API. 

We can use these definitions for unhashing the plugin name/variant/pip url/ etc. 

Scope:

- [ ] Create tap or modify https://github.com/AutoIDM/tap-meltanohub
- [ ] Configure extractor in project
- [ ] dbt staging models

**Comment by aaronsteers** [comment]
@pnadolny13 - To confirm, I think you mean pulling in the hub's plugin definitions, yes?

Could we rename to `Ingest Hub Plugin Definitions` if so for clarity?

(Landed here from the ref in meltano/hub#570.)
