### ISSUE TITLE
Implement Cluster Auto Scaling for Squared Project

### ISSUE THREAD

**Issue by pnadolny13** [meltano/squared#288]
Relates to https://github.com/meltano/squared/issues/278

The k8s cluster resources are statically provisioned right now which is somewhat inefficient during low utilitization times. Additionally were seeing some issues related to deployments failing likely because of blue/green deployments maxing out our resources.

cc @kgpayne cc @tayloramurphy

**Comment by tayloramurphy** [comment]
@pnadolny13 I see this is in the Engineering Assignments project - are you planning on picking this up or were you needing Engineering assistance?

**Comment by pnadolny13** [comment]
@tayloramurphy I think this is more appropriate for someone like Ken. Especially because it will touch the reusable terraform module. I added it to the engineering board so you could help prioritize when to do it 😄 .

**Comment by tayloramurphy** [comment]
@pnadolny13 let's sync on this in our next 1:1

**Comment by tayloramurphy** [comment]
Closing for the squared project as this is basically an upgrade to our existing cluster.
