### ISSUE TITLE
Re-implement Hub Metrics At Variant Level

### ISSUE THREAD

**Issue by pnadolny13** [meltano/squared#298]
Following the telemetry changes where we have variant level data, we should re-implement our dbt models to calculate metrics at the variant level. The hub will also need to be updated to consume them at that level, if not already.

Scope:
- reimplement the dbt models
- write a new set of yaml files to S3 while continuing to send the original versions
- the hub needs to be updated to use the new set of files before the original files can be removed

**Comment by aaronsteers** [comment]
@pnadolny13 - Thanks for logging. Does it appear we are receiving data clean enough and usable for this purpose? Aka, any blockers you can see? :) 

In terms of metrics, could we include "successful" as a criteria on the project count and also the execution count? Something like:

1. # Projects Installed
   - Same as today's "Num Projects" basically and _includes_ projects that have never had a successful execution.
2. # Successful Executions
   - Same as today basically, except filtering for "success".
   - Should includes `meltano el` or `meltano run` executions.
   - Ideally should exclude things like `--config` or `--dump`, and `--dry-run`/`--dry` which would not actually execute the extractor/loader.
3. # Projects with 1+ Execution
   - This gives a numerator of "successful" to the distinct "total projects installed" view, providing a clue to where problems should be expected.

A widely used stable tap might look like this:

- `# Projects Installed (Last 3 months)`: 1,234
- `# Projects with 1+ Execution (Last 3 months)`: 1,101
- `# Successful Executions (Last 3 months)`: 40,123

A brand new tap with some tricky auth might look like this:

- `# Projects Installed (Last 3 months)`: 4
- `# Projects with 1+ Execution (Last 3 months)`: 2
- `# Successful Executions (Last 3 months)`: 423

A much-wanted but not-yet-working tap might look like this:

- `# Projects Installed (Last 3 months)`: 350
- `# Projects with 1+ Execution (Last 3 months)`: 2
- `# Successful Executions (Last 3 months)`: 200

**Comment by pnadolny13** [comment]
I'm going to close this because its a duplicate of https://github.com/meltano/hub/issues/570
