### ISSUE TITLE
Filter out short-lived project IDs and/or add a flag for filtering

### ISSUE THREAD

**Issue by aaronsteers** [meltano/squared#323]
Today when evaluating how many project IDs we have on various cloud providers, we may be seeing noise related to auto-created "ephemeral" IDs that are generated and then evaporated because they are executed in a container. It would not be sufficient to use 'project_id_source' because only the first invocation of the Meltano CLI will have that flag of being autogenerated. In a typical workflow, the first command might be 'meltano install' but then subsequent commands like 'meltano run` or 'meltano elt' may or may not have the same project ID source flag.

## Objectives

1. We want to have cleaner (or higher confidence) project count numbers when analyzing metrics such as "num deployments per cloud" and "num projects successfully using plugins".
1. Project IDs with a very short lifetime (<3 hours, for instance) should not count towards "total distinct projects" metrics.

## Challenges

I think the objective here would be to exclude project IDs with a lifecycle less than (for instance) 4-6 hours. A challenge would be how to distinguish "this ran with a container for 4 hours and we never saw it again" vs "this user played around with meltano for 4 hours and we never saw them again".

Maybe the better solution is to use a project age filter of "2+ days" on metrics that attempt to analyze how meltano is being used in the wild. And then metrics related to attrition and new-user experience might have a different filter or a different metric for distinct project IDs.

@pnadolny13 and @tayloramurphy - What do you think? Can we have use a cleansed project count for our standard "Num Distinct Project IDs" and just have separate reports on "Short-Lived Project IDs" when we talk about same-day customer attrition? Several filter options could work for short-lived project ID analysis: <1 day, <2 days, or <6 hours should all work for this case.

**Comment by pnadolny13** [comment]
@aaronsteers thats a good point about how project source works.

>Maybe the better solution is to use a project age filter of "2+ days" on metrics that attempt to analyze how meltano is being used in the wild. And then metrics related to attrition and new-user experience might have a different filter or a different metric for distinct project IDs.

I cant says for sure that 2+ days is the number were looking for vs 3+ vs 12hr+, but I like that idea of distinguishing between a short lived execution that looks like a user vs an actual short lived user that churns. We could use multiple filter options until we narrow down on our assumptions about churning new users and how long they explore for before leaving. I can also do a deeper dive on this to get a better sense, the data is there I just havent dug into it yet to know.

**Comment by aaronsteers** [comment]
This came up again in #385 - since it appears to be affecting usability of metrics, it might be worth prioritizing sooner than later.

**Comment by pnadolny13** [comment]
Theres been a lot of work on this related to non-bot and ephemeral projects. I'm going to close this for now but if we have more issues in the future we can continue iterating.
