### ISSUE TITLE
Squared Pods Fail to Start

### ISSUE THREAD

**Issue by pnadolny13** [meltano/squared#325]
For https://github.com/meltano/squared/issues/289 I merged this PR https://github.com/meltano/squared/pull/317 which had some bugs related to generating the DAGs so I pushed https://github.com/meltano/squared/pull/322. The DAGs now load and the commands render properly but when they try to run a pod it starts for like <5s then errors out without any relevant logs that I can find.

I didnt actually change anything other than the generation of the DAGs, the `MeltanoKubernetesPodOperator` calls all stay the same. The only change is whats being sent to the `MeltanoKubernetesPodOperator` but I dont see anything that could cause this, including in case its helpful.

```python
      task = MeltanoKubernetesPodOperator(
          task_id=task_id,
          name=task_name,
          environment="prod",
          log_level=meltano_log_level, # Comes from Variable.get("MELTANO_LOG_LEVEL", "info")
          arguments=[cmd],
          dag=dag,
          retry_delay=retry_delay,
      )
```
vs the new 

```python
    task = MeltanoKubernetesPodOperator(
        task_id=task_id, # comes from f"meltano_{schedule['name']}_{schedule['job']['name']}_tasks{index}"
        name=task_id,
        environment=os.environ.get('MELTANO_ENVIRONMENT'),
        log_level=os.environ.get('MELTANO_CLI_LOG_LEVEL'),
        arguments=[f'meltano run {run_args}'],
        dag=dag,
        # retry_delay=retry_delay,
    )
```

I'm thinking that its a problem with the cluster itself or the docker images, its almost like they cant access the image or something but its there and available.

**Comment by pnadolny13** [comment]
cc @tayloramurphy I was wasting a bunch of time on this was paused to get some work done. I've just been manually running the pipelines since its only once a day. I can dig into it more but it would also be helpful to get some assistance from someone who has k8s debugging experience, maybe Ken can help next week when hes back.

**Comment by tayloramurphy** [comment]
@aaronsteers we definitely need some help from engineering on this one. Happy to sync on it but right now Pat has to basically run everything manually.

**Comment by aaronsteers** [comment]
This may be a good opportunity to move the workflows to a simpler architecture, and at the same time start a how-to doc for end users who may want to use MWAA or another managed Airflow option:

- https://github.com/meltano/squared/issues/326

**Comment by aaronsteers** [comment]
@pnadolny13 - You mentioned there's not much of a log or error message. Can you provide what you are seeing? Also, can you provide the AWS region name and cluster ID for debugging? Thanks!

**Comment by aaronsteers** [comment]
@pnadolny13 - [This log on the airflow instance](http://internal-095a2699-meltano-airflowai-4cc5-148256298.us-east-1.elb.amazonaws.com/log?dag_id=meltano_slack_el_slack_el&task_id=meltano_slack_el_slack_el_task0&execution_date=2022-07-26T16%3A52%3A55.785831%2B00%3A00) has the following snippet:

```
                                  {'name': 'MELTANO_CLI_LOG_LEVEL',
                                   'value': None,
                                   'value_from': None},
```

This tells me the newly mapped env vars are (one or both) probably evaluating to `None`, which could be causing the 'failure to start' behavior. This could also be happening with the `MELTANO_ENVIRONMENT` variable also but I didn't see it referenced in the log.


@pnadolny13 - Can you please try adding a guard condition here so the failure will occur before sending to the operator? And/or please replace/revert back to hardcoded values:

```
        environment=os.environ.get('MELTANO_ENVIRONMENT'),
        log_level=os.environ.get('MELTANO_CLI_LOG_LEVEL'),
```

Example guard condition would be:

```py
    environment_name = os.environ.get('MELTANO_ENVIRONMENT')
    if not environment:
        raise ValueError("Environment cannot be blank of missing.")

    log_level = os.environ.get('log_level')
    if not log_level:
        raise ValueError("Environment cannot be blank of missing.")
```

And then you can use the pre-tested values:

```
    task = MeltanoKubernetesPodOperator(
        task_id=task_id, # comes from f"meltano_{schedule['name']}_{schedule['job']['name']}_tasks{index}"
        name=task_id,
        environment=environment_name,
        log_level=log_level,
        arguments=[f'meltano run {run_args}'],
        dag=dag,
        # retry_delay=retry_delay,
    )
```

**Comment by pnadolny13** [comment]
@aaronsteers that worked! Thanks for the help unblocking me
