### ISSUE TITLE
Added vs churned vs reactivated

### ISSUE THREAD

**Issue by pnadolny13** [meltano/squared#346]
Following the deep dive into PxP projects, it would be good to turn some of the ad hoc queries into dbt models that we can look at more consistently.

I created a query for diffing the 28d rolling projects against the previous period to understand how many were added, churned, and of the added projects how many were active some time in the past and are just being reactivated again. I was doing a comparison between months but it might be better to do a daily diff that we can roll up. 

- use a base table for 28 rolling look back of active projects so we can query the project ids if needed, currently thats done in a CTE then aggregated so we dont have it anywhere for shared use.
- find a way to do a minus operations between 2 periods in a loop. My initial attempt caused errors about invalid subqueries. For the ad hoc analysis I was doing this manually by hard coding date ranges.
- explore how to expose this data, is there a way to show added and churned alongside the total?

**Comment by pnadolny13** [comment]
Branch with analytical queries and base update https://github.com/meltano/squared/tree/project_plugin_analysis

**Comment by pnadolny13** [comment]
@tayloramurphy FYI I added a cool chart to the daily dashboard that shows the monthly inflows and outflows of active projects now that this work is completed.

**Comment by tayloramurphy** [comment]
@pnadolny13 thanks for sharing! This brings up other questions too 😄
