### ISSUE TITLE
Create S3 bucket for data dumps/backups

### ISSUE THREAD

**Issue by afolson** [meltano/squared#352]
I'd like to grab a backup of our data from Orbit. At the moment this is just a CSV and there's no need to put it into Snowflake/some other store.

cc @pnadolny13

**Comment by pnadolny13** [comment]
@tayloramurphy Amanda and I talked in slack about this last week. I was thinking I'd do https://github.com/meltano/squared/issues/247 and create a prefix for this orbit backup data.

Does that make sense?

**Comment by tayloramurphy** [comment]
@pnadolny13 works for me. Just add to Engineering Assignments project when you pick it up.
