### ISSUE TITLE
Refactoring to use new finer grain of event attributes

### ISSUE THREAD

**Issue by pnadolny13** [meltano/squared#361]
https://github.com/meltano/squared/pull/324 finished parsing individual events at a finer grain. I think there might be one or two other events that weren't needed yet that should be parsed appropriately, then all downstream models should use them instead of the execution level roll up used for initial development https://github.com/meltano/squared/blob/main/data/transform/models/marts/telemetry/base/unstructured_parsing/unstruct_exec_flattened.sql.

Scope:
- full coverage of unstructured events parsed independently
- deprecate the `unstruct_exec_flattened` model or remove all attributes that the wrong grain
- refactor downstream models to stop using `unstruct_exec_flattened` for event level attributes

**Comment by pnadolny13** [comment]
Consider having a table/view that includes all attribute similar to the execution level roll up so we can use it when debugging. I believe right now sometimes we still need to go to the raw data for certain things which is a huge pain since many events make up an execution and you need to flatten the context to stitch them together before retrieving highly nested values. Nobody should have to query the raw table ever.

**Comment by pnadolny13** [comment]
While working on this - I was wondering if theres ever a chance that a cli command would get more more than 1 subcommand. Is it safe to assume 2 levels max i.e. command and subcommand? I see cli->schedule->list. Could or would we ever do something like cli -> schedule -> list -> x? I'm not sure the use case for that our how it would work but I'm also not very familiar with our click CLI setup.

```json
[
    {
      "data": {
        "command": "cli",
        "options": {
          "environment": null,
          "log_config": null,
          "log_level": null,
          "no_environment": false,
          "verbose": 0
        },
        "parent_command_hint": null
      },
      "schema": "iglu:com.meltano/cli_context/jsonschema/1-1-0"
    },
    {
      "data": {
        "command": "schedule",
        "options": {
          "database_uri": null
        },
        "parent_command_hint": "cli"
      },
      "schema": "iglu:com.meltano/cli_context/jsonschema/1-1-0"
    },
    {
      "data": {
        "command": "list",
        "options": {
          "format": "fb97b451af8304805c66b24f082d2abf4b747a1e84b163bbc91033c85e251eb6"
        },
        "parent_command_hint": "schedule"
      },
      "schema": "iglu:com.meltano/cli_context/jsonschema/1-1-0"
    }
  ]
```

@pandemicsyn @aaronsteers @edgarrmondragon @tayloramurphy

**Comment by tayloramurphy** [comment]
@pnadolny13 I don't see anything in https://docs.meltano.com/contribute/cli#consistent-definition-of-groups-commands-sub-commands-arguments-and-options about limiting the depth. Seems like it should be rare, but I would guess it's posible.
