### ISSUE TITLE
bug - pipeline surrogate key inputs inconsistent

### ISSUE THREAD

**Issue by pnadolny13** [meltano/squared#369]
I noticed a bug in the way that I was generating pipeline surrogate keys where the key changes because the same plugins are in a different order than the last time the key was generated. In https://github.com/meltano/squared/blob/4880d587d1a6b78e4e5c43f755ac750f83b40cf3/data/transform/models/marts/telemetry/base/pipeline_executions.sql#L6 we create an array of plugins using [ARRAY_AGG](https://docs.snowflake.com/en/sql-reference/functions/array_agg.html) but its not ordered.

**Comment by pnadolny13** [comment]
@tayloramurphy this looks like it will adjust the unique pipelines number down slightly from what we were previously reporting. Its still the same trend but a few projects that have large composable pipelines were looking like multiple unique pipelines when they shouldnt.

**Comment by pnadolny13** [comment]
@tayloramurphy The other thing I noticed and I'm not sure its considered a bug or not but if a project is pinning their plugin version and they bump it then it is considered a new pipeline because pip url is an attribute that makes the plugin unique. Is that expected behavior from your view or would you expect pip url to be excluded from the definition of a plugin? If so, what attributes make up a unique plugin as its used for pipelines. 

- name
- parent_name
- variant
- pip_url
- executable
- namespace
- plugin_type

**Comment by tayloramurphy** [comment]
@pnadolny13 including pip_url makes sense to me as it shows a change to the platform.
