### ISSUE TITLE
Implement Project Activity Filters for Hub Metrics

### ISSUE THREAD

**Issue by pnadolny13** [meltano/squared#385]
I noticed that target-sqlite has a low success rate as of today 205 projects vs 12 successful projects. Thats weird. I installed it and was able to use it no problem, it was actually unusually easy to use. I did a quick exploration and it looks like a ton of the projects are failing or aborting on add. The majority look like theyre random project ID source. Its possible that a single user is blowing up the metrics and a plugin look very good or bad, which is misleading.

This makes me wonder if we should be filtering out usage for random project ID source somehow.

cc @aaronsteers because I know youre interested in these metrics. Let me know if you have thoughts.

**Comment by aaronsteers** [comment]
@pnadolny13 - Thanks for researching this and sharing this finding.

Yes, I think we should remove short-lived / random project IDs from these metrics. More specifically, I think we should suppress them from the 'projects' metrics. When looking at the activity under `tap-gitlab` I doubt that this is actually the most actively used tap, and I think it's very likely that shortly-lived CI pipelines are grossly inflating that metric.

From your data, do you think a filtering out of project less than a couple hours would be sufficient?

 Related to:

- #323

**Comment by pnadolny13** [comment]
I changed the name of this since tap-sqlite is just one example.

Following https://github.com/meltano/squared/issues/440 we can filter out projects based on our funnel analysis and what were considering to be valid project activity. Exclude things like `is_ci_only` and lifespan less than x mins/hours, etc.
