### ISSUE TITLE
Primary Metric - underlying model clean up

### ISSUE THREAD

**Issue by pnadolny13** [meltano/squared#400]
As part of https://github.com/meltano/internal-data/issues/19 and https://github.com/meltano/internal-data/issues/18 I did a lot of ad hoc analysis. I ended up writing a bunch of queries in metabases sql editor in order to explore properly. Thats messy and not sustainable. Some of it could have been supported if the right fields were exposed.

fact_cli_executions:
- cli runtime ms
- pipeline runtime binning, first iteration was:
  - 5 sec and 10 sec
  - 10 sec and 30 sec
  - 30 sec and 1 min
  - 1 min and 3 mins
  - 3 mins and 5 mins
  - 5 mins and 10 mins
  - 10 mins and 30 mins
  - 30 mins and 1 hr
  - 1 hr and 3 hr

fact_plugin_usage
- pipeline_fk

project_dim:
- life span in days (relevant PR https://github.com/meltano/squared/pull/387)

PIpeline distribution:
- median (not supported by metabase)
- execution count binning (I dont know where this would go, its post aggregation)
  - 1
  - between 2 and 5
  - between 6 and 50
  - between 51 and 100
  - between 101 and 500
  - between 501 and 1,500
  - between 1,501 and 5,000
  - between 5,001 and 10,000
  - between 10,001 and 100,000
  - >= 100,001

**Comment by tayloramurphy** [comment]
@pnadolny13 is part of this issue getting some of the charts you made in https://github.com/meltano/internal-data/issues/18 into Superset?

**Comment by pnadolny13** [comment]
The pipeline distribution piece is post aggregation so I wont be adding these to the dbt models, I can do the binning in the BI tool if we need it.
