### ISSUE TITLE
Create Read Only User For tap-snowflake Testing

### ISSUE THREAD

**Issue by pnadolny13** [meltano/squared#424]
Related to https://github.com/MeltanoLabs/tap-snowflake/pull/2#issuecomment-1257890462. 

>@pnadolny13 once this merges, it would be good to start using it in squared 😅 Also, do we have a sanitised Snowflake user/database/warehouse that we can use for testing? I have been using internal creds for development, but it would be good to create some tests that utilise an example Snowflake instance that is 'safe' to be used in the MeltanoLabs context. A read-only user with access to example data should be more than sufficient 🙂

**Comment by pnadolny13** [comment]
We can create a read only user that has access to the [sample data that Snowflake provides](https://docs.snowflake.com/en/user-guide/sample-data.html) when you create an account. Would that work?

Looking ahead, would we also need a place for the target to write data during testing or is that already figured out? Maybe I should create a new database like `MELTANO_LABS_TEST` (or similar) including a `SAMPLE_DATA` schema with a clone of the snowflake sample data and a `TARGET_TEST` (or similar) for writing data.

**Comment by tayloramurphy** [comment]
@pnadolny13 yeah, a wholly separate database and user would be good. They'll also likely need permissions to create and destroy their own DBs and stages.
