### ISSUE TITLE
Migrate to MeltanoLabs tap-snowflake

### ISSUE THREAD

**Issue by pnadolny13** [meltano/squared#425]
Once https://github.com/MeltanoLabs/tap-snowflake/pull/2 merges we should test out that new tap and migrate once were comfortable.

**Comment by pnadolny13** [comment]
This PR is failing CI because of https://github.com/MeltanoLabs/tap-snowflake/issues/10. It makes it hard to toggle schema/database across environments. Currently all isolated CI envs are being accessed by the tap vs just its own.

**Comment by tayloramurphy** [comment]
@pnadolny13 if it's not ready for primetime then let's wait until that issue is complete 👍
