### ISSUE TITLE
feat: Adopt `BATCH` message type in a small selection of taps and targets, for testing

### ISSUE THREAD

**Issue by kgpayne** [meltano/squared#432]
With [tap-snowflake](https://github.com/MeltanoLabs/tap-snowflake) and [target-snowflake](https://github.com/MeltanoLabs/target-snowflake) close to completing their first usable iteration, it would be good to test them on a 'real' project.

For us to make use of `tap-snowflake`, the following targets should be updated to v0.11.1 of the SDK:

- [target-yaml](https://github.com/MeltanoLabs/target-yaml)

For us to make use of `target-snowflake`, the following taps should be updated to v0.11.1 of the SDK:

- [tap-slack](https://github.com/MeltanoLabs/tap-slack)
- [tap-github](https://github.com/MeltanoLabs/tap-github)

**Comment by aaronsteers** [comment]
Closing. Stale.
