### ISSUE TITLE
feat: Meltano Slack Channel Subscribing to All Hub Listed Repos

### ISSUE THREAD

**Issue by pnadolny13** [meltano/squared#455]
The fact that Singer/Meltano connectors are mostly spread out across lots of different org and user github namespaces, it would be awesome to have a slack channel that auto subscribes to all hub listed tap/target repos. Similar to hub-repo-activity so we can see issues and PR status. Obviously a small number of people would want to opt into this but I think having a holistic view of the ecosystem would help us (Meltano) and anyone else in the community keep on top of contributions and statuses so contributions don't get ghosted or bugs get logged as issues but go unnoticed.

This is a good example https://github.com/voxmedia/tap-twitter/pull/2#issue-1301016819 of a PR that didn't reference anyone so it went unnoticed for a while. I stumbled on it and got a quick reply after @'ing the maintainers but it probably would have otherwise been ignored. We could help keep on top of some of these things as the main Singer ecosystem organizers right now if it was easy to monitor the ecosystem.

I don't know how much traffic we get so this might become less useful if its too noisy. Maybe we can try manually creating a channel and subscribing to a bunch of the top used repos pipelinewise/singer-io/meltanolabs/a few others and see how that goes, then potentially automate subscribing using a bot that reads the Hub API periodically.

cc @tayloramurphy @sbalnojan @aaronsteers @afolson what do you all think?

**Comment by afolson** [comment]
@pnadolny13 Is there anything I can do to make less work for you? 😅

**Comment by aaronsteers** [comment]
> but maybe if its useful we can think about how to push it to Slack.

@pnadolny13 - What about using `target-apprise` or similar at the end of an ELTP pipeline to push to Slack?

**Comment by pnadolny13** [comment]
@afolson I'll let you know once I dig into it a little more but down the line I'll definitely need help around figuring out the best way to share this info and what our processes are for using it. Like should we go ping people on issues/PRs and how long to wait, etc.

@aaronsteers oh good idea I forgot about that target!

**Comment by pnadolny13** [comment]
This is completed - see the singer-ecosystem-activity channel https://meltano.slack.com/archives/C0489728QFL
