### ISSUE TITLE
Create Staging Environment For Managed

### ISSUE THREAD

**Issue by pnadolny13** [meltano/squared#467]
- review https://github.com/meltano/squared/pull/462
- create staging snowflake DBs
- give permissions to MELTANO role to use the staging DBs
- test that config and new DBs work together
- share with engineering some jobs that are low risk and idempotent for testing
  - pulumi managed schedules are defined in https://github.com/meltano/dragon-infra/pull/50
- New S3 bucket or prefix for hub metrics publish to write to in staging env
  - potentially consider https://github.com/meltano/squared/issues/247 as part of this
- Find a way to disable Slack notifications if in staging, maybe URI is local vs Slack?

cc @tayloramurphy @aaronsteers

**Comment by aaronsteers** [comment]
> - Find a way to disable Slack notifications if in staging, maybe URI is local vs Slack?

For this item, how about we just create a #slack-automation-test-output channel that we all ignore or mute when not testing integrations?

**Comment by pnadolny13** [comment]
@aaronsteers I think thats a good idea. I'll look into it but it requires me to create a new webhook (also refreshing my existing one) in order to write to a different channel. So we'd need to have 2 sets of credentials, 1 for prod and one for staging. I think opting to exclude this job for the first iteration might be the easiest.

**Comment by pnadolny13** [comment]
After some thought following https://github.com/meltano/squared/pull/462#issuecomment-1301222629 I think a reasonable plan is:
- create STAGING_PROD/STAGING_PREP/STAGING_RAW databases
- create STAGING user and role
- create replica meltano environment config (what this PR does)
- alter replica config
  - use STAGING user and role along with pointing to STAGING_X databases
  - use S3 bucket `staging` prefix
  - re: slack alerts [above](https://github.com/meltano/squared/issues/467#issuecomment-1301160037) override slack uri in .env with something else (TBD) 
- Ken will commit an encoded version of our prod .env file except the `SNOWFLAKE_PASSWORD` entry which is adjusted to use the STAGING user's password

This will allow us to run everything in managed testing using `--environment=staging` without any risk of altering prod. This is a "prod like replica". Once everything is working and done we flip the switch by committing updates to the encoded .env pointing back to the prod MELTANO snowflake user, S3 bucket path, and slack URI. Managed will update to use `--environment=prod` instead of staging.

**Comment by aaronsteers** [comment]
@pnadolny13 - This sounds like a good plan! I know the snowflake-side work to create the DBs, user, and role may be time consuming but I see the benefit of not worrying if a misconfigured environment or command might run code against the wrong target.

cc @tayloramurphy - other alpha users may have similar concerns, and admittedly, it's not a trivial effort.
