### ISSUE TITLE
Ingesting Cloudwatch Logs

### ISSUE THREAD

**Issue by pnadolny13** [meltano/squared#506]
Related to slack thread https://meltano.slack.com/archives/C03GKHWS0HM/p1670877270980859 and https://github.com/meltano/squared/issues/108 that will come after this.

We need a pattern for getting cloudwatch logs into Snowflake. Current use cases:
- hub api logs
- meltano cloud logs

From slack:
> AJ: We're going to have a lot of cases where this is needed.
A few options:
> - Use Kinesis to process the Cloudwatch log streams.
> - Create something like tap-cloudwatch-logs to Meltano-ify the problem.
> - Create something like tap-datadog-logs to Meltano-ify the problem (one step downstream).
> - Setup a Cloudwatch-to-S3 flow, where specific Cloudwatch logs would automatically get dumped to S3.

https://aws.amazon.com/premiumsupport/knowledge-center/cloudwatch-logs-retrieve-data/
https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/SubscriptionFilters.html
https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/S3Export.html

**Comment by pnadolny13** [comment]
It seems like the lowest lift way to get cloudwatch logs to snowflake would be the tap approach. I found this example script https://stackoverflow.com/questions/59240107/how-to-query-cloudwatch-logs-using-boto3-in-python/59254837#59254837  that basically does the core of what the tap needs to do.


One thing I'm not totally sure about is the cost effectiveness of this vs something like a native sync to S3. Queries are charged based on bytes scanned so in theory its like a tap-athena or tap-bigquery. Using it wisely in incremental mode would presumable solve it but cloud cost estimates is not something I have much experience with.

**Comment by aaronsteers** [comment]
I like the `tap-cloudwatch` approach because it gives us a powerful new extractor option on the Hub. That said, other options might be more streamlined with AWS itself. 🤷‍♂️

Regarding cost comparison, I can't speak to this but maybe @magreenbaum has some ideas.

**Comment by magreenbaum** [comment]
> It seems like the lowest lift way to get cloudwatch logs to snowflake would be the tap approach. I found this example script https://stackoverflow.com/questions/59240107/how-to-query-cloudwatch-logs-using-boto3-in-python/59254837#59254837 that basically does the core of what the tap needs to do.
> 
> One thing I'm not totally sure about is the cost effectiveness of this vs something like a native sync to S3. Queries are charged based on bytes scanned so in theory its like a tap-athena or tap-bigquery. Using it wisely in incremental mode would presumable solve it but cloud cost estimates is not something I have much experience with.
> 
> @kgpayne @aaronsteers @magreenbaum do you know anything about this? Does it seem like a reasonable solution to you?

I'm not familiar enough with snowflake at the moment to say which option is better from an architecture standpoint. S3 is durable and easy to query vs I'm not sure how cloudwatch log querying would hold up. I'm also wondering if snowflake has their own suggested methods for ingesting cloudwatch logs. 

Regarding cost though here are my thoughts:

Looks like the example script from @pnadolny13's comment is using `start_query` and `stop_query` which are CloudWatch Logs Insights queries. Pricing on this is $0.005 per GB of data scanned (Logs Insights queries) based on paid tier in [this](https://aws.amazon.com/cloudwatch/pricing/) doc. Data transfer out costs `$0.02` per GB (from `us-west-2` to `us-east-1` where squared is running). The big cost is ingesting to CloudWatch logs to begin with but API GW currently only supports ingestion to CloudWatch Logs anyway (no s3 direct option). 

As far as s3 syncs, guessing this would be `COPY` or `GET` operations which would cost either `$0.005` or `$0.0004` respectively per 1,000 requests (based on [this](https://aws.amazon.com/s3/pricing/) doc). We'd need an intermediary step to export CW logs to s3 (or kinesis -> s3) though and that cost will be `$0.25` per GB (first 10TB) for either of those options. 

It depends on how many requests vs how much data we'd be scanning but I have no objections to the cloudwatch query approach. It seems like the simplest approach.

**Comment by pnadolny13** [comment]
@tayloramurphy I have https://github.com/pnadolny13/tap-cloudwatch thats in a pretty good place, it still needs some minor readability refactors and to add more tests but it works well so far. I also have a draft PR up to add it to squared https://github.com/meltano/squared/pull/521. What do you think about moving it out of my namespace and into meltanolabs? I can add it to the hub once we decide where it will live.
