### ISSUE TITLE
tap-postgres: Airflow/Meltano/Superset RDS instances

### ISSUE THREAD

**Issue by pnadolny13** [meltano/squared#519]
We have 3 RDS postgres instances for the Squared self hosted deployment. It could be a good use case to use tap-postgres to replicate data from one of them (probably the most active) in cloud. This would help test several things at once:

1. we have a DB replication use case in cloud. Its not super high volume but it could be a good stress test, potentially down the line trying to run it every 5-10 mins like lots of users do.
2. it would use the new tap-postgres https://github.com/MeltanoLabs/tap-postgres and help raise any bugs
3. it would help us come up with a meltano cloud pattern for accessing DBs in private networks because alpha/beta users will likely need this almost immediately

If we wanted to do this I'd probably do this:
- get it working on our self hosted deployment where networking isnt a problem. Schedule it to run every hour
- migrate to cloud where we figure out access patterns
- increase frequency of schedule incrementally and see how cloud performs - 30 mins, 20 mins ,10 mins, 5 mins?

@tayloramurphy @aaronsteers @magreenbaum what do you think about this?

**Comment by tayloramurphy** [comment]
@pnadolny13 It'd be worth making sure it works for us, so I'm definitely supportive.

**Comment by magreenbaum** [comment]
Thinking a bit on implementation for this: this would require clients to provide us some sort of VPN access or maybe this is related (ssh tunneling to connect to a private db): https://github.com/meltano/cloud-planning/issues/81 in which case we'd need to configure an ssh private key and ssh-agent on the runner if I understand that correctly. Which would relate to [this](https://github.com/meltano/infra/issues/189) issue as well.
