### ISSUE TITLE
Optimize large table runtime with incremental models

### ISSUE THREAD

**Issue by pnadolny13** [meltano/squared#524]
The event telemetry dbt models take a long time to rebuild every night, one particular model `unstruct_event_flattened` blocks everything downstream for almost an hour. We can easily make these speed up by using incremental models.

Its not an immediate issue since we only use an x-small warehouse so the cost is low and we only refresh once a day but it would hugely benefit the days where we need to rerun failed jobs, or refresh after a deployment.

**Comment by pnadolny13** [comment]
To follow up on this - it ended up leading to a 38% decrease in runtime. So its completes in ~75 mins vs 120. Which is ~22.5 hrs a month @ $6 per hour  = $135 per month savings.

The total node runtime increase by about 5 mins but the parallelization allowed the queries to distribute better and optimize the available threads better. Theres still more incremental logic we can add to reduce this further but this is a good start.

cc @tayloramurphy

**Comment by tayloramurphy** [comment]
Amazing @pnadolny13 nice work!
