### ISSUE TITLE
Parse bad environment contexts

### ISSUE THREAD

**Issue by pnadolny13** [meltano/squared#542]
This [PR](https://github.com/meltano/meltano/pull/7256) was part of realizing that the new environment context schema was not registered properly with snowcat cloud so those contexts were being failed for schema violations. We still have those events but theyre in a separate bad events table and dont flow through dbt, so no data loss as far as I can tell but theyre not contributing to our metrics. Potentially new user metrics the most because new users are most likely to pip install the latest version.

This affected meltano versions 2.14.0 and 2.15.0 from Jan 23rd to Feb 1st. On the worst day Jan 29th we excluded ~7% of events due to this. Without looking too deep I think this would cause most executions to go missing for that date range and meltano versions because environment context is sent with almost all cli events.

This potentially solves https://github.com/meltano/squared/issues/257 also if we find a way to sustainably do this generically vs a one off for this environments situation.

cc @tayloramurphy @DouweM

**Comment by tayloramurphy** [comment]
@pnadolny13 agreed this is worth looking at so we can get that data back in. Do you suspect this will have an effect on our primary metrics for January? If so we should probably wait on the monthly update until we have this sorted cc @DouweM

**Comment by pnadolny13** [comment]
@tayloramurphy its hard to tell until I parse those events more but just taking a guess I would think that the new user metrics are affected because anyone who found meltano for the first time and ran pip install meltano will get the newest release that was the affected version for the week or so that it was an issue. I doubt it will impact pipelines since most production users are slower to upgrade.

**Comment by pnadolny13** [comment]
@tayloramurphy FYI I got these failed events parsed and back into our metrics, the updates I'm seeing are:
- new projects metric jumped up a lot from where it was yesterday to about even with last month
- active projects got a slight bump of maybe 5-10 projects
- pipeline counts were tipped over the edge from 1.87M to 1.88M
- the funnel metrics base counts increased a lot so it looks inline with the trend vs a drop WoW. The >5 mins level raw count 2023-01-23 I think was in the 70's yesterday and today is ~160 which looks a lot more like we'd expect.
