### ISSUE TITLE
Bug: `tap-github` and `tap-gitlab` have stale git refs, preventing `meltano install` from succeeding

### ISSUE THREAD

**Issue by aaronsteers** [meltano/squared#559]
@pnadolny13 - You're probably already aware of this but tap-github and tap-gitlab each are still pinned to a commit ref or a branch ref - and it looks like both refs are stale at this point.

Is it okay to move these back to a pinned version ref for each?

Not a priority per se. I am using `squared` to repro a separate issue, and ran into this when testing.

**Comment by aaronsteers** [comment]
Update: maybe there was some other issue. On rerunning, the process has not failed. Apologies for the false alarm.

**Comment by pnadolny13** [comment]
@aaronsteers yeah the CI pipelines would fail on this so we'd get alerted pretty quickly but it is a good reminder that I should review the old git tags and probably do some upgrade 😄 .
