### ISSUE TITLE
Fully Migrate to Cloud

### ISSUE THREAD

**Issue by pnadolny13** [meltano/squared#611]
Currently I have staging jobs running in cloud but the production jobs are still in the self managed Airflow/EKS deployment. I feel comfortable that the cloud features are sufficient enough to replace Airflow. These are the steps for migrating:

1. Create a new cloud deployment for production
2. Migrate secrets from parameter store to Cloud
3. Create all schedules in the production deployment
4. Migrate singer state to cloud
- Cloudwatch
- Google Analytics
- Slack
- Github/Gitlab?
5. Enable all schedules

Features that I'd want to confirm before migrating:
- state migration - I believe theres currently no way to to self service move my state but engineering would "white glove" migrate me. I'd have to check but its also possible that I could let them all full refresh although its preferred and good practice to migrate.
- secrets migration
  - I see theres a config set command on the CLI now which should be sufficient for most
  - In the past we had an issue with secrets being too big. @aaronsteers @kgpayne Do either of you know if thats still an issue? I think that was for the google credentials json file that I'm storing in a single env var.

This would allow us to:
- scale down the EKS cluster to only support Superset
- delete the Airflow deployment and postgres db
- delete the meltano deployment and postgres db

Follow ons:
- scale down self hosted infrastructure
- remove github actions workflow for building/deploying

@tayloramurphy @aaronsteers is there anything that I'm missing that would stop me from fully migrating to cloud?

- [x] cloudwatch-el
- [x] dynanmodb-el
- [x] github-meltano-el
- [x] github-search-el
- [x] gitlab-el
- [x] google-analytics-el
- [x] hub-metrics-publish
- [x] hubspot-publish
- [x] marts-refresh
- [x] meltanohub-el
- [x] slack-el
- [x] snowplow-el
- [x] slack-notifications
- [x] spreadsheets-anywhere-el

**Comment by tayloramurphy** [comment]
> is there anything that I'm missing that would stop me from fully migrating to cloud

@pnadolny13 not to my knowledge. 

Regarding Superset - I would be open to moving to a hosted platform for BI just so we don't have to worry about it in the short term. That said, if it's not too much trouble to keep it self-hosted I'm fine to do that, but it _is_ another  bit of infra to maintain and watch.

**Comment by pnadolny13** [comment]
@tayloramurphy I created https://github.com/meltano/squared/issues/478 to spike on what infra we have after migrating to cloud and what we should do with it. In the short run we could always scale down our cluster to a single instance (if thats allowed) and just leave Superset on, while we figure out next steps.

**Comment by aaronsteers** [comment]
> In the past we had an issue with secrets being too big. @aaronsteers @kgpayne Do either of you know if thats still an issue? I think that was for the google credentials json file that I'm storing in a single env var.

@pnadolny13 - Recent conversations in the bigquery-dev channel in slack seem to suggest we should be okay with size of env vars overall - but still be confirmed if there's any Cloud-specific limitation. Can you try this out and confirm for us?

**Comment by pnadolny13** [comment]
@magreenbaum would you be able to assist with getting a `prod` deployment created for Squared?

I also need all the schedules listed in https://github.com/meltano/squared/blob/53b21c223043ae10169b9fc2ba14e816ce547069/data/orchestrate/orchestrators.meltano.yml#L13 added to the deployment. They should all be added as disabled so I can manage slowly adding secrets, testing that they work, running backfills, then deactivating my Airflow jobs.

**Comment by kgpayne** [comment]
@pnadolny13 just a heads up, it looks like the current Squared infrastructure is monitored and in-scope for Drata (the SOC2 platform we are using). The data platform wasn't built to comply with SOC2, so if there is an affordable option to move self-managed Superset to a hosted platform, that would allow us to side-step a chunk of work that would otherwise be in with our SOC2 certification 🙂 FYI @tayloramurphy @magreenbaum

**Comment by tayloramurphy** [comment]
@kgpayne @pnadolny13 killing that infra and migrating to Preset would be a quick way to ease some burden on compliance issues. I'd be willing to bet we could use their CLI to export from our instance and hopefully quickly upload to Preset.

**Comment by magreenbaum** [comment]
@pnadolny13 I've added a prod deployment and the new schedules. All the new schedules are disabled by default. 

Schedules are not environment specific right now so staging and prod both have the same schedule added to them. [Related](https://github.com/meltano/meltano/issues/6853). They're all disabled and need to be enabled to use them.

**Comment by pnadolny13** [comment]
@kgpayne I opened https://github.com/meltano/squared/issues/478 for that topic! Migrating to Preset seems reasonable.

@magreenbaum thanks!

**Comment by pnadolny13** [comment]
@magreenbaum @cjohnhanson How does cloud tell meltano what environment to use when running my schedule? e.g. `--environment=x` or setting `MELTANO_ENVIRONMENT` or something else 🤷 ? I'm curious because I see  `MELTANO_ENVIRONMENT` as one of secrets set in the squared project and I'm wondering if that would override and cause weird behavior.

I removed it from squared but it might be an edge case to consider if my secret takes precedence I think that would mean I can run different meltano environments in the same cloud deployment when I think cloud deployments are supposed to map 1-1 with environments.

**Comment by magreenbaum** [comment]
@pnadolny13 when the schedule kicks off, the container command is specifying `meltano --environment <environment_name> schedule run <schedule_name>`. I don't know if `MELTANO_ENVIRONMENT` would take precedence. Maybe @cjohnhanson or @WillDaSilva can confirm. I think we'd want to not have that env var set in the cloud. If it does override, maybe we want to document that or always unset this before running our meltano command in our bootstrap script.

**Comment by pnadolny13** [comment]
@magreenbaum ok great, let me know if you need me to open an issue or anything around that.

Separate issues:
- I'm getting this error when trying to run my prod job
```
[2023-04-21T19:22:26+00:00] Starting entry script
[2023-04-21T19:22:26+00:00] PWD: /project
[2023-04-21T19:22:26+00:00] Setting short-lived GitHub Access Token
Traceback (most recent call last):
  File "/github/get_token.py", line 18, in <module>
    installation_id = client.get_installation_id(owner)
  File "/github/meltano_github_utils/__init__.py", line 219, in get_installation_id
    raise GitHubAppNotInstalledError
meltano_github_utils.GitHubAppNotInstalledError
```

**Comment by magreenbaum** [comment]
@pnadolny13 sorry about that. I quick-fixed the problem and opened an issue in [infra](https://github.com/meltano/infra/issues/689) about it. 

Regarding the schedule names, for now we should use the schedule names that are in the `meltano.yml` file to run jobs. This is a known inconsistency that is being worked on. Further deets related in [this comment here](https://github.com/meltano/infra/pull/688#discussion_r1174050696).

**Comment by pnadolny13** [comment]
This done! I have all schedules enabled in cloud. I was able to set start dates using secrets configs for all the schedules with state and ran them manually so they will have proper state moving forward.
