### ISSUE TITLE
Spike: Singer Guild Metrics

### ISSUE THREAD

**Issue by pnadolny13** [meltano/squared#624]
Related to the original implementation in https://github.com/meltano/squared/issues/104.

This would be a second iteration to align on a few metrics that the Singer guild cares about and have them available in a dashboard so we can review them at guild meetings. The existing Singer Ecosystem Activity [dashboard](http://internal-095a2699-meltano-superset-608a-2127736714.us-east-1.elb.amazonaws.com/superset/dashboard/14/) which shows some similar data to what is sent to #singer-ecosystem-activity in slack. 

Some metrics that might be interesting:

### Connectors
- Issues and PRs - potentially split out by meltano/labs vs other
  - open/close/merge rate
  - PRs/issues open count
  - PRs/issues open length
  - length of time from open to close
- number of contributors/maintainers
- number of new connectors created
- SDK based repos

### Hub repo
- plugin count - distinct and all variants
- legacy vs SDK
  - total listed
  - total default
  - total with >X projects using it or >X executions monthly
- maybe connector counts that are database vs api vs etc.

### SDK repo
- SDK issues
- SDK contributors
- usage volume SDK vs legacy (projects and executions) - this would give us a nice "X % if projects use SDK plugins" and only "X % of projects are still using legacy plugins" or "most of our execution volume is going through SDK variants

### MeltanoLabs
- count of connectors vs other
- count of default on the hub
- count of contributors
- similar issues/PR metrics listed above e.g. counts, open/close rate, etc.
- singer most wanted count

cc @edgarrmondragon @kgpayne

**Comment by edgarrmondragon** [comment]
Thanks for compiling this list @pnadolny13! I think we have some telemetry on Meltano errors, but can we tell which plugin caused the failure?

**Comment by pnadolny13** [comment]
@edgarrmondragon its not 100% explicit but I'm able to do a pretty decent job parsing out which plugin caused the error. See https://github.com/meltano/squared/blob/e892635a302e475902d1bf9c501d0534e3fc1c68/data/transform/models/marts/telemetry/base/plugin_executions.sql#L79. I used the exit code + exception + position in a command (for `run`) to tease out which failed. I falls back to `UNKNOWN_FAILED_OR_ABORTED` if theres not enough info or I'm not confident in which one caused the failure.

**Comment by edgarrmondragon** [comment]
@pnadolny13 nice! That could help us know if failures in certain plugins leads to folks forking an existing variant or creating a new one from scratch. If we don't address that, the variant/fork proliferation might become unmanageable 😅

Another that might be useful to know is whether folks switch pip URLs (e.g. when they create a fork) and whether they switch back, which ties to maintainer responsiveness, that is whether they merge PRs and publish new releases.

**Comment by pnadolny13** [comment]
Theres a lot to do here but I started a new singer guild metrics dashboard and put a few charts in there https://3bea8a0b.us1a.app.preset.io/superset/dashboard/18/?native_filters_key=qB-Z4mNTpt3h5wQA9MzVgAF6HdtJnuRfMIApp31egrwrAdnFk6WqkqGYd5rEwD9I. We can keep iterating on this but I'm going to close this spike issue in exchange for a few more implementation issues.
