### ISSUE TITLE
Spike: How to replicate Metronome credit usage data

### ISSUE THREAD

**Issue by pnadolny13** [meltano/squared#653]
This replaces https://github.com/meltano/squared/issues/632. 

Theres an existing Metronome tap https://hub.meltano.com/extractors/tap-metronome, explore whether that does what we need. If not, fork it to or contribute changes to it.

Another consideration is Metronome's export feature as mentioned in https://github.com/meltano/infra/issues/628#issuecomment-1600982297.

**Comment by magreenbaum** [comment]
1). Is there an extra cost associated for data exporting?
- data export is charged at .02 per 1k events exported (this is in contract) and counts toward your credit. It usually ends up being a very small amount as you typically only export a subset of your overall events.
2) If we have issues with data exporting, would we open a support request to get that fixed/replicating again?
- yes support will work with you
3) Do you run full exports daily i.e. trunc and load?
- Here is what can be exported: https://docs.metronome.com/exporting-your-data/#what-can-be-exported and it is exported daily
4) What info would you need from us to set that up?
- what destination would you use? We can then turn on the feature and send documentation

**Comment by pnadolny13** [comment]
@magreenbaum thanks for getting that info!

I explored the API and existing tap a bit more and it looks like its totally possible to pull the same data using the API/tap although at least 1 stream "credit grants" is missing so I'd have to add that. Also the exported data looks like its normalized a bit relative to the API responses i.e. line items are their own table in the export vs a nested dict in the API/tap data. That means we'd need a bit more work on the dbt staging logic to make the data usable. Another thing thats a little weird is that I think all API token are read and write, I dont see a way to create an API token for Squared thats read only.

Its hard to understand how much with will cost give the 0.02 per 1k events exported but right now the export is seeming like the preferred approach. Any idea how many events we'd be generating

**Comment by magreenbaum** [comment]
I don't know right now the exact number but it'll be dependent on how many customers we have and how many pipelines they run. The raw ingested usage events will be the highest. This is the usage data per run that we send to metronome. Right now it's looking like each pipeline run will send at max 3 events. That could change but I think it's safe to estimate 3 right now. The more customers running workloads and the more frequent pipelines that get added will increase event ingestion the most. 

Good point regarding the read/write API token. I'll ask about that info to see if there are plans to make permissions configurable for tokens. I think the tap will still require an API token to use so either way we can't get around that. 

If it's quick and easy to use their export feature and you think switching to using a tap later won't be too terrible, I'm fine going the export route and deferring the work. We can see how much that ends up costing and if it's too much we can switch to tap.

**Comment by pnadolny13** [comment]
@magreenbaum Ben answered my question in slack:

>Hi Pat, regarding it being a small amount. Most of our customer don't export raw events, instead just the other data types therefore it is significantly less than the amount of events you ingest.
>
>yes navigate to > General Settings and configure Data Export here

I'm able to see the self service page where I can configure what data to export so I think this is probably a good path forward for now.

## Decision:

I'll plan to configure the native data exports from Metronome to Snowflake because its likely low cost, avoids the work needed to use the tap, and avoids the risks due to the limitation of all API tokens being read and write. I will configure it to not export any of the raw event data because its expensive and probably doesnt add much value anyways. We can monitor the cost and if its something we want to optimize out of we can switch to using the tap/API in the future.
